version: "3"
services:
  port-service:
    build: "."
    read_only: true
    container_name: port-service
    hostname: port-service
    depends_on:
      - postgres
    volumes:
      - ./data/:/data/
    environment:
      - FILE_SOURCE=/data/ports.json
      - PG_DSN=postgres://admin:admin123@postgres:5432/postgres?sslmode=disable
    deploy:
      resources:
        limits:
          memory: 200M

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=postgres
    volumes:
      - /var/lib/postgresql/data
    restart: always
